// @generated by packages/appBuild/routesBuild.ts
import { iso } from "packages/app/__generated__/__isograph/iso.ts";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Query.EntrypointBlog`)
iso(`entrypoint Query.EntrypointContentFoundryApp`)
iso(`entrypoint Query.EntrypointBlogPost`)
iso(`entrypoint Query.EntrypointTwitterIdeator`)
iso(`entrypoint Query.EntrypointTwitterIdeatorWorkshop`)
iso(`entrypoint Query.EntrypointTwitterIdeatorVoice`)
iso(`entrypoint Query.EntrypointTwitterIdeatorWorkshopPermalink`)
iso(`entrypoint Query.EntrypointTwitterIdeatorCompose`)
iso(`entrypoint Query.entrypointTwitterIdeatorResearchPermalink`)
iso(`entrypoint Query.entrypointTwitterIdeatorResearch`)
iso(`entrypoint Query.EntrypointHome`)
iso(`entrypoint Query.EntrypointFormatter`)
iso(`entrypoint Query.EntrypointFormatterVoice`)
iso(`entrypoint Query.entrypointFormatterEditor`)

import entrypointBlog from "packages/app/__generated__/__isograph/Query/EntrypointBlog/entrypoint.ts"
import entrypointContentFoundryApp from "packages/app/__generated__/__isograph/Query/EntrypointContentFoundryApp/entrypoint.ts"
import entrypointBlogPost from "packages/app/__generated__/__isograph/Query/EntrypointBlogPost/entrypoint.ts"
import entrypointTwitterIdeator from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeator/entrypoint.ts"
import entrypointTwitterIdeatorWorkshop from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorWorkshop/entrypoint.ts"
import entrypointTwitterIdeatorVoice from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorVoice/entrypoint.ts"
import entrypointTwitterIdeatorWorkshopPermalink from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorWorkshopPermalink/entrypoint.ts"
import entrypointTwitterIdeatorCompose from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/entrypoint.ts"
import entrypointTwitterIdeatorResearchPermalink from "packages/app/__generated__/__isograph/Query/entrypointTwitterIdeatorResearchPermalink/entrypoint.ts"
import entrypointTwitterIdeatorResearch from "packages/app/__generated__/__isograph/Query/entrypointTwitterIdeatorResearch/entrypoint.ts"
import entrypointHome from "packages/app/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts"
import entrypointFormatter from "packages/app/__generated__/__isograph/Query/EntrypointFormatter/entrypoint.ts"
import entrypointFormatterVoice from "packages/app/__generated__/__isograph/Query/EntrypointFormatterVoice/entrypoint.ts"
import entrypointFormatterEditor from "packages/app/__generated__/__isograph/Query/entrypointFormatterEditor/entrypoint.ts"

export {entrypointBlog};
export {entrypointContentFoundryApp};
export {entrypointBlogPost};
export {entrypointTwitterIdeator};
export {entrypointTwitterIdeatorWorkshop};
export {entrypointTwitterIdeatorVoice};
export {entrypointTwitterIdeatorWorkshopPermalink};
export {entrypointTwitterIdeatorCompose};
export {entrypointTwitterIdeatorResearchPermalink};
export {entrypointTwitterIdeatorResearch};
export {entrypointHome};
export {entrypointFormatter};
export {entrypointFormatterVoice};
export {entrypointFormatterEditor};
