// @generated by packages/appBuild/routesBuild.ts
import { iso } from "packages/app/__generated__/__isograph/iso.ts";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Query.EntrypointContentFoundryApp`)
iso(`entrypoint Query.EntrypointBlogPost`)
iso(`entrypoint Query.entrypointTwitterIdeatorResearchPermalink`)
iso(`entrypoint Query.EntrypointDocsPost`)
iso(`entrypoint Query.entrypointTwitterIdeatorResearch`)
iso(`entrypoint Query.EntrypointTwitterIdeatorWorkshopPermalink`)
iso(`entrypoint Query.EntrypointTwitterIdeatorCompose`)
iso(`entrypoint Query.EntrypointTwitterIdeatorVoice`)
iso(`entrypoint Query.EntrypointTwitterIdeatorWorkshop`)
iso(`entrypoint Query.EntrypointDocs`)
iso(`entrypoint Query.EntrypointBlog`)
iso(`entrypoint Query.EntrypointTwitterIdeator`)

import entrypointContentFoundryApp from "packages/app/__generated__/__isograph/Query/EntrypointContentFoundryApp/entrypoint.ts"
import entrypointBlogPost from "packages/app/__generated__/__isograph/Query/EntrypointBlogPost/entrypoint.ts"
import entrypointTwitterIdeatorResearchPermalink from "packages/app/__generated__/__isograph/Query/entrypointTwitterIdeatorResearchPermalink/entrypoint.ts"
import entrypointDocsPost from "packages/app/__generated__/__isograph/Query/EntrypointDocsPost/entrypoint.ts"
import entrypointTwitterIdeatorResearch from "packages/app/__generated__/__isograph/Query/entrypointTwitterIdeatorResearch/entrypoint.ts"
import entrypointTwitterIdeatorWorkshopPermalink from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorWorkshopPermalink/entrypoint.ts"
import entrypointTwitterIdeatorCompose from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/entrypoint.ts"
import entrypointTwitterIdeatorVoice from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorVoice/entrypoint.ts"
import entrypointTwitterIdeatorWorkshop from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorWorkshop/entrypoint.ts"
import entrypointDocs from "packages/app/__generated__/__isograph/Query/EntrypointDocs/entrypoint.ts"
import entrypointBlog from "packages/app/__generated__/__isograph/Query/EntrypointBlog/entrypoint.ts"
import entrypointTwitterIdeator from "packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeator/entrypoint.ts"

export {entrypointContentFoundryApp};
export {entrypointBlogPost};
export {entrypointTwitterIdeatorResearchPermalink};
export {entrypointDocsPost};
export {entrypointTwitterIdeatorResearch};
export {entrypointTwitterIdeatorWorkshopPermalink};
export {entrypointTwitterIdeatorCompose};
export {entrypointTwitterIdeatorVoice};
export {entrypointTwitterIdeatorWorkshop};
export {entrypointDocs};
export {entrypointBlog};
export {entrypointTwitterIdeator};
